import { Component, OnInit } from '@angular/core';
import { DatePipe, NgFor, NgIf } from '@angular/common';
import { RouterLink } from '@angular/router';
import { Job, JobStatus } from '../core/models';
import { JobsService } from '../core/jobs.service';
import { AuthService } from '../core/auth.service';

@Component({ standalone: true, imports: [NgFor, NgIf, DatePipe, RouterLink], template: `
  <header class="page-header"><div><div class="eyebrow">Tuesday, August 18</div><h1>Good morning, {{ firstName }}.</h1><p class="subtle">Here is the shape of your search right now.</p></div><a routerLink="/jobs" class="primary-button">+ Add application</a></header>
  <section class="stat-grid"><div class="stat-card accent"><span class="stat-label">Active pipeline</span><strong>{{ activeCount }}</strong><span class="trend">↑ {{ activeCount ? '12' : '0' }}% <small>vs last month</small></span></div><div class="stat-card"><span class="stat-label">Interviews</span><strong>{{ interviewCount }}</strong><span class="stat-note">{{ interviewCount ? 'Keep the momentum' : 'Your next one is waiting' }}</span></div><div class="stat-card"><span class="stat-label">Response rate</span><strong>{{ responseRate }}<small>%</small></strong><span class="stat-note">Across all applications</span></div><div class="stat-card"><span class="stat-label">Offers</span><strong>{{ offerCount }}</strong><span class="stat-note">The finish line is visible</span></div></section>
  <div class="view-switch"><button [class.selected]="visualizer === 'pulse'" (click)="visualizer = 'pulse'">Pulse</button><button [class.selected]="visualizer === 'kanban'" (click)="visualizer = 'kanban'">Kanban</button><button [class.selected]="visualizer === 'sankey'" (click)="visualizer = 'sankey'">Sankey flow</button><button [class.selected]="visualizer === 'funnel'" (click)="visualizer = 'funnel'">Funnel</button></div>
  <div class="dashboard-grid" *ngIf="visualizer === 'pulse'"><section class="panel pipeline-panel"><div class="panel-heading"><div><div class="eyebrow">Pipeline pulse</div><h2>Applications by stage</h2></div><a routerLink="/jobs" class="text-link">View all →</a></div><div class="pipeline-bars"><div class="pipeline-row" *ngFor="let item of pipeline"><div class="row-meta"><span>{{ item.label }}</span><b>{{ item.count }}</b></div><div class="bar-track"><div class="bar-fill" [style.width.%]="item.width" [class]="item.color"></div></div></div></div></section><section class="panel activity-panel"><div class="panel-heading"><div><div class="eyebrow">Recent activity</div><h2>Latest updates</h2></div></div><div class="activity" *ngIf="jobs.length; else empty"><span class="activity-dot"></span><div><strong>{{ jobs[0].company }}</strong><p>{{ jobs[0].title }}</p></div><time>{{ jobs[0].updatedAtUtc | date:'MMM d' }}</time></div><ng-template #empty><div class="empty-state">Add your first application to see activity here.</div></ng-template></section></div>
  <section class="panel visualizer-panel" *ngIf="visualizer === 'kanban'"><div class="panel-heading"><div><div class="eyebrow">Drag-ready pipeline</div><h2>Kanban board</h2></div></div><div class="kanban"><div class="kanban-column" *ngFor="let item of pipeline"><div class="row-meta"><span>{{ item.label }}</span><b>{{ item.count }}</b></div><div class="kanban-card" *ngFor="let job of jobsFor(item.status)"><strong>{{ job.company }}</strong><span>{{ job.title }}</span></div><div class="kanban-empty" *ngIf="!jobsFor(item.status).length">Nothing here yet</div></div></div></section>
  <section class="panel visualizer-panel" *ngIf="visualizer === 'sankey'"><div class="panel-heading"><div><div class="eyebrow">Flow of the hunt</div><h2>Applied to outcome</h2></div></div><div class="sankey"><div class="flow-node">Applied <b>{{ jobs.length }}</b></div><span class="flow-line">→</span><div class="flow-node purple">Interview <b>{{ interviewCount }}</b></div><span class="flow-line">→</span><div class="flow-node green">Offer <b>{{ offerCount }}</b></div></div><p class="subtle flow-footnote">Rejections and ghosted applications remain visible in your outcome history.</p></section>
  <section class="panel visualizer-panel" *ngIf="visualizer === 'funnel'"><div class="panel-heading"><div><div class="eyebrow">Conversion health</div><h2>Application funnel</h2></div></div><div class="funnel"><div class="funnel-step one"><span>Applied</span><b>{{ jobs.length }}</b></div><div class="funnel-step two"><span>Responded</span><b>{{ respondedCount }}</b></div><div class="funnel-step three"><span>Interviewed</span><b>{{ interviewCount }}</b></div><div class="funnel-step four"><span>Offer</span><b>{{ offerCount }}</b></div></div></section>
  <section class="panel chart-panel"><div class="panel-heading"><div><div class="eyebrow">Search rhythm</div><h2>Applications over time</h2></div><span class="period-pill">Last 6 weeks · All statuses</span></div><div class="chart"><div class="y-axis"><span>12</span><span>8</span><span>4</span><span>0</span></div><div class="chart-area"><div class="grid-line" *ngFor="let line of [1,2,3,4]"></div><div class="columns"><div class="column" *ngFor="let height of [32,48,42,65,52,78]"><div class="column-fill" [style.height.%]="height"></div></div></div><div class="x-axis"><span *ngFor="let day of ['Jul 14','Jul 21','Jul 28','Aug 04','Aug 11','Today']">{{ day }}</span></div></div></div></section>` })
export class DashboardComponent implements OnInit {
  jobs: Job[] = [];
  visualizer = 'pulse';
  constructor(private readonly jobsService: JobsService, private readonly auth: AuthService) {}
  ngOnInit(): void { this.jobsService.list().subscribe({ next: jobs => this.jobs = jobs }); }
  get firstName(): string { return this.auth.user()?.displayName.split(' ')[0] || 'there'; }
  get activeCount(): number { return this.jobs.filter(job => !['Rejected', 'Ghosted', 'JobOffer'].includes(job.status)).length; }
  get interviewCount(): number { return this.jobs.filter(job => job.status === 'Interview').length; }
  get offerCount(): number { return this.jobs.filter(job => job.status === 'JobOffer').length; }
  get respondedCount(): number { return this.jobs.filter(job => job.status !== 'Ghosted').length; }
  get responseRate(): number { return this.jobs.length ? Math.round(((this.jobs.length - this.jobs.filter(job => job.status === 'Ghosted').length) / this.jobs.length) * 100) : 0; }
  get pipeline(): { label: string; status: JobStatus; count: number; width: number; color: string }[] { const values = [{ label: 'Waiting', status: 'Waiting' as JobStatus, color: 'orange' }, { label: 'Interview', status: 'Interview' as JobStatus, color: 'purple' }, { label: 'Job offer', status: 'JobOffer' as JobStatus, color: 'green' }, { label: 'Rejected', status: 'Rejected' as JobStatus, color: 'gray' }]; const max = Math.max(1, ...values.map(value => this.jobs.filter(job => job.status === value.status).length)); return values.map(value => ({ ...value, count: this.jobs.filter(job => job.status === value.status).length, width: (this.jobs.filter(job => job.status === value.status).length / max) * 100 })); }
  jobsFor(status: JobStatus): Job[] { return this.jobs.filter(job => job.status === status); }
}
