import { Component, OnInit } from '@angular/core';
import { FormsModule } from '@angular/forms';
import { NgIf } from '@angular/common';
import { AuthService } from '../core/auth.service';
import { PreferencesService } from '../core/preferences.service';
import { Preferences } from '../core/models';

@Component({ standalone: true, imports: [FormsModule, NgIf], template: `
  <header class="page-header"><div><div class="eyebrow">Workspace controls</div><h1>Settings</h1><p class="subtle">Make SufferTracker work like you do.</p></div></header>
  <div class="settings-layout"><nav class="settings-nav"><a class="active">Profile</a><a>Preferences</a><a>Security</a><a>Danger zone</a></nav><section class="settings-content"><div class="panel settings-panel"><div class="panel-heading"><div><div class="eyebrow">Profile</div><h2>Your details</h2></div></div><label>Display name<input [(ngModel)]="displayName"></label><label>Email address<input [(ngModel)]="email" type="email"></label><label>New password <small>Leave blank to keep your current password.</small><input [(ngModel)]="password" type="password"></label><button class="primary-button" (click)="saveProfile()">Save profile</button><span class="save-message" *ngIf="message">{{ message }}</span></div><div class="panel settings-panel"><div class="panel-heading"><div><div class="eyebrow">Preferences</div><h2>How you see the hunt</h2></div></div><div class="setting-line"><div><strong>Dark mode</strong><p>Keep the interface easy on your eyes.</p></div><button class="toggle" [class.on]="preferences.darkMode" (click)="preferences.darkMode = !preferences.darkMode"><span></span></button></div><div class="setting-line"><div><strong>MFA protection</strong><p>Authenticator setup is ready for the next security provider.</p></div><button class="toggle" [class.on]="preferences.mfaEnabled" (click)="preferences.mfaEnabled = !preferences.mfaEnabled"><span></span></button></div><label>Default dashboard view<select [(ngModel)]="preferences.defaultView"><option value="kanban">Kanban board</option><option value="sankey">Sankey flow</option><option value="funnel">Funnel chart</option></select></label><label>Interview rounds <strong class="range-value">{{ preferences.interviewRounds }}</strong><input type="range" min="1" max="10" [(ngModel)]="preferences.interviewRounds"></label><button class="secondary-button" (click)="savePreferences()">Save preferences</button></div><div class="panel danger-panel"><div><div class="eyebrow">Danger zone</div><h2>Delete account</h2><p>This permanently removes your profile and every application.</p></div><button class="danger-button" (click)="deleteAccount()">Delete account</button></div></section></div>` })
export class SettingsComponent implements OnInit {
  email = ''; displayName = ''; password = ''; message = ''; preferences: Preferences = { darkMode: true, defaultView: 'kanban', interviewRounds: 3, mfaEnabled: false };
  constructor(private readonly auth: AuthService, private readonly preferenceService: PreferencesService) {}
  ngOnInit(): void { const user = this.auth.user(); if (user) { this.email = user.email; this.displayName = user.displayName; } this.preferenceService.get().subscribe({ next: value => { this.preferences = value; this.preferenceService.applyTheme(value.darkMode); } }); }
  saveProfile(): void { this.auth.updateProfile(this.displayName, this.email, this.password).subscribe({ next: () => { this.password = ''; this.message = 'Profile saved.'; }, error: () => this.message = 'Could not save profile.' }); }
  savePreferences(): void { this.preferenceService.update(this.preferences).subscribe({ next: () => this.message = 'Preferences saved.' }); }
  deleteAccount(): void { if (confirm('Permanently delete your account and applications?')) this.auth.deleteAccount().subscribe({ next: () => this.auth.logout() }); }
}
